import type {
  InsightPayload,
  InsightResult,
  KpiKey,
} from "../types/domain";
import { KPI_DEFINITIONS } from "../types/domain";

const OPENAI_API_URL = "https://api.openai.com/v1/chat/completions";

function buildInsightPrompt(payload: InsightPayload): string {
  const kpiDef = KPI_DEFINITIONS.find((k) => k.key === payload.kpi);
  const kpiLabel = kpiDef ? kpiDef.label : payload.kpi;

  const topDriversText = payload.topDrivers
    .sort((a, b) => b.causality_score - a.causality_score)
    .slice(0, 5)
    .map(
      (d, index) =>
        `${index + 1}. Driver: ${d.driver}, causality_score: ${d.causality_score.toFixed(
          2
        )}, contribution_estimate: ${(d.contribution_estimate * 100).toFixed(
          1
        )}%`
    )
    .join("\n");

  const anomaliesText =
    payload.anomalies.length === 0
      ? "No anomalies detected for this KPI in the last 7 vs previous 7 window."
      : payload.anomalies
          .map((a) => {
            const changePct = (a.delta * 100).toFixed(1);
            return `KPI: ${a.kpi}, change: ${changePct}%, last window: ${a.lastWindow.startDate} → ${a.lastWindow.endDate}`;
          })
          .join("\n");

  const segmentHighlightsText =
    payload.segmentHighlights.length === 0
      ? "No specific segment highlights were provided."
      : payload.segmentHighlights.join("\n");

  return `
You are an analytics and product expert.

The KPI we are analyzing is: ${kpiLabel} (${payload.kpi}).

KPI trend summary:
${payload.kpiTrendSummary}

Top drivers (with causality scores and contribution estimates):
${topDriversText || "No drivers available."}

Segment highlights:
${segmentHighlightsText}

Anomalies (last 7 vs previous 7 days):
${anomaliesText}

Task:
Write a clear, business-friendly explanation in 3–4 short paragraphs.
Explain:
- what happened to the KPI,
- which drivers most likely explain the change and why,
- how different segments might be affected,
- and what actions the team should consider.

Avoid mentioning 'correlation', 'causality_score', or raw numeric details directly.
Speak like a senior data-informed PM explaining to stakeholders.
Use concise, concrete language, not fluff.
`;
}

function buildMockInsight(payload: InsightPayload): InsightResult {
  const kpiDef = KPI_DEFINITIONS.find((k) => k.key === payload.kpi);
  const kpiLabel = kpiDef ? kpiDef.label : payload.kpi;

  const topDriver = payload.topDrivers[0];

  const mainDriverText = topDriver
    ? `The primary suspected driver is "${topDriver.driver}", which appears to explain a large part of the recent movement in ${kpiLabel}.`
    : `No dominant driver stands out for ${kpiLabel} based on the current synthetic data.`;

  return {
    kpi: payload.kpi,
    text: [
      `This is a mock AI insight generated locally without calling OpenAI. The KPI "${kpiLabel}" shows a recent movement, but the magnitude is relatively modest in the last 7 days compared to the prior 7-day window.`,
      mainDriverText,
      `Because this is a synthetic environment or the OpenAI API key is not configured, treat this explanation as a placeholder. In a real deployment, this text would be replaced by a richer explanation generated by the OpenAI API using the same payload.`,
    ].join("\n\n"),
    createdAt: new Date().toISOString(),
  };
}

export interface AiExplainOptions {
  apiKeyOverride?: string; 
  model?: string; 
}

export async function generateInsightForKpi(
  payload: InsightPayload,
  options: AiExplainOptions = {}
): Promise<InsightResult> {
  const apiKey =
    options.apiKeyOverride || import.meta.env.VITE_OPENAI_API_KEY;

  const model = options.model || "gpt-4.1-mini";

  if (!apiKey) {
    console.warn(
      "[aiExplain] No OpenAI API key found (VITE_OPENAI_API_KEY). Using mock insight."
    );
    return buildMockInsight(payload);
  }

  const prompt = buildInsightPrompt(payload);

  try {
    const response = await fetch(OPENAI_API_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        messages: [
          {
            role: "system",
            content:
              "You are a senior product & data leader explaining KPI movements to business stakeholders.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
      }),
    });

    if (!response.ok) {
      console.error(
        "[aiExplain] OpenAI API error:",
        response.status,
        await response.text()
      );
      return buildMockInsight(payload);
    }

    const data = (await response.json()) as {
      choices?: { message?: { content?: string } }[];
    };

    const text =
      data.choices?.[0]?.message?.content ||
      "AI response was empty. This is a fallback message.";

    return {
      kpi: payload.kpi,
      text,
      createdAt: new Date().toISOString(),
    };
  } catch (err) {
    console.error("[aiExplain] Error calling OpenAI:", err);
    return buildMockInsight(payload);
  }
}
